# Generated by Django 5.0.3 on 2024-04-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='health_files/plans/')),
                ('tags', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NutritionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='health_files/plans/')),
                ('tags', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='fitnessevaluation',
            name='workout_or_meal_plan',
            field=models.FileField(upload_to='health_files/fitness_evaluations/'),
        ),
    ]
