# Generated by Django 5.0.3 on 2024-04-02 18:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_first_name', models.CharField(max_length=100)),
                ('player_last_name', models.CharField(max_length=100)),
                ('player_birthday', models.DateField()),
                ('player_club', models.CharField(max_length=100)),
                ('player_position', models.CharField(max_length=100)),
                ('emergency_contact_first_name', models.CharField(max_length=100)),
                ('emergency_contact_last_name', models.CharField(max_length=100)),
                ('emergency_contact_email', models.EmailField(max_length=254)),
                ('emergency_contact_phone', models.CharField(max_length=20)),
                ('photo_release_form', models.FileField(upload_to='photo_release_forms/')),
                ('liability_waiver', models.FileField(upload_to='liability_waivers/')),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camp.camp')),
            ],
        ),
    ]
