# Generated by Django 5.0.3 on 2024-04-03 03:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0002_campregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachCampRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach_first_name', models.CharField(max_length=100)),
                ('coach_last_name', models.CharField(max_length=100)),
                ('coach_email', models.EmailField(max_length=254)),
                ('coach_phone', models.CharField(max_length=20)),
                ('coach_club', models.CharField(max_length=100)),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camp.camp')),
            ],
        ),
    ]
