# Generated by Django 5.0.3 on 2024-04-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0003_coachcampregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campregistration',
            name='liability_waiver',
            field=models.FileField(upload_to='camp_files/liability_waivers/'),
        ),
        migrations.AlterField(
            model_name='campregistration',
            name='photo_release_form',
            field=models.FileField(upload_to='camp_files/photo_release_forms/'),
        ),
    ]
