# Generated by Django 5.0.3 on 2024-04-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0004_alter_campregistration_liability_waiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='coach_payment_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='camp',
            name='player_payment_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
