# Generated by Django 5.0.3 on 2024-04-16 23:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0005_camp_coach_payment_link_camp_player_payment_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('coach', 'Coach'), ('player', 'Player')], max_length=10)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('club', models.CharField(blank=True, max_length=100)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('emergency_contact_first_name', models.CharField(max_length=100)),
                ('emergency_contact_last_name', models.CharField(max_length=100)),
                ('emergency_contact_email', models.EmailField(max_length=254)),
                ('emergency_contact_phone', models.CharField(max_length=20)),
                ('photo_release_form', models.FileField(blank=True, upload_to='camp_files/photo_release_forms/')),
                ('liability_waiver', models.FileField(blank=True, upload_to='camp_files/liability_waivers/')),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('has_paid', models.BooleanField(default=False)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camp.camp')),
            ],
        ),
    ]
