# Generated by Django 5.0.3 on 2024-04-22 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0008_camp_coach_price_camp_details_camp_player_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='crest',
            field=models.FileField(blank=True, upload_to='camp_files/camp_crests/'),
        ),
    ]
